import datetime
import os
import re
import time
from tkinter.constants import S
import keyboard
import openpyxl
import pyautogui
import pymsgbox
from keyboard import press
from selenium import webdriver
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common import by
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

options = Options()
options.add_argument("nwapp=C:/Program Files (x86)/LSTV/POS/frontend/KRAKEN_RESTO.exe")

driver = webdriver.Chrome("C:/Users/SERAN/Desktop/Selenium Jar Files/nwjs-sdk-v0.54.0-win-x64/chromedriver", options= options)
driver.maximize_window()

time.sleep(3)
# LOG IN 
driver.find_element_by_xpath("/html/body/ion-app/ion-modal/div/page-setup/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input").send_keys(Keys.BACKSPACE)
time.sleep(1)
driver.find_element_by_xpath("/html/body/ion-app/ion-modal/div/page-setup/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input").send_keys(4)
driver.find_element_by_xpath("/html/body/ion-app/ion-modal/div/page-setup/ion-content/div[2]/form/ion-card/ion-grid/ion-row[6]/ion-col[2]/ion-item/div[1]/div/ion-input/input").send_keys(80)
time.sleep(1)
driver.find_element_by_xpath("/html/body/ion-app/ion-modal/div/page-setup/ion-content/div[2]/form/ion-card/ion-grid/ion-row[8]/ion-col/button[2]/span").click()
time.sleep(2)
driver.switch_to.alert.accept() 
time.sleep(5)
driver.find_element_by_xpath("/html/body/ion-app/ion-modal/div/page-security-code/ion-content/div[2]/ion-grid/ion-row[5]/ion-col[2]/input").send_keys("CCW-PCH-TPP-AWA-EXH-PNO-AHP-NWX-NNP-ZRW")
time.sleep(1)
driver.find_element_by_xpath("/html/body/ion-app/ion-modal/div/page-security-code/ion-content/div[2]/ion-grid/ion-row[6]/ion-col/button/span").click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-login/ion-content/div[2]/ion-grid/ion-row[1]/ion-col/form/ion-card/ion-list/ion-item[1]/div[1]/div/ion-input/input").send_keys("lstv")
driver.find_element_by_xpath("/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-login/ion-content/div[2]/ion-grid/ion-row[1]/ion-col/form/ion-card/ion-list/ion-item[2]/div[1]/div/ion-input/input").send_keys("lstventures")
time.sleep(1)
driver.find_element_by_xpath("/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-login/ion-content/div[2]/ion-grid/ion-row[1]/ion-col/form/div/button[1]/span").click()
time.sleep(3)


driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-home/ion-content/div[2]/ion-list/button[6]/span').click()
time.sleep(1)
def setUp():
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[15]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-memc/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-memc-crud/ion-content/div[2]/form/ion-card/ion-row/ion-col/ion-item[1]/div[1]/div/ion-input/input').send_keys('MEMC 1')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-memc-crud/ion-content/div[2]/form/ion-card/ion-row/ion-col/ion-item[2]/div[1]/div/ion-input/input').send_keys(100)
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-memc-crud/ion-content/div[2]/form/ion-card/ion-col/ion-row/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-memc/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[4]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-terminal/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-terminal-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('T1')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-terminal-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('127.0.0.1')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-terminal-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-terminal/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[5]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-locations/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-locations-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('Printer Station')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-locations-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
    time.sleep(1)
    
    press ('enter')
    time.sleep(1)
    press ('enter')
    time.sleep(1)
    press ('enter')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-locations-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[4]/div[1]/ion-radio/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-locations-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[4]/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-locations-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[4]/ion-col[2]/ion-item/div[1]/div/ion-input/input').send_keys('80')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-locations-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[5]/ion-col/button[3]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-locations/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[6]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-area-code/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-area-code-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('Computation_area')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-area-code-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[2]/ion-col/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-area-code/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[7]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-tables/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-tables-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('Computation_table')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-tables-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-tables-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('4')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-tables-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[6]/ion-col/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-tables/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[8]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-item-class/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-class-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('FOODS')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-class-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-class-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-item-class/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[9]/div[1]/div/ion-label').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-item-subclass/ion-content/div[1]/ion-fab/button/ion-icon').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-subclass-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-subclass-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys('Dish')
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-subclass-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-subclass-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-item-subclass-crud/ion-content/div[2]/form/ion-card/ion-grid/ion-row[4]/ion-col/button[2]/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-item-subclass/ion-header/ion-navbar/ion-buttons/button').click()
    time.sleep(1)


setUp()


path = "C:/Users/SERAN/Desktop/POS_TESTING/SCENARIO 1.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active
row = 34

item = []
unitCost = []
sellingPrice = []
reOrderLevel = []

#item
for index in range(4, row + 1):
    cell_obj = sheet_obj.cell(row = index, column = 1)
    item.append(cell_obj.value)

for index in range(4, row + 1):
    cell_obj = sheet_obj.cell(row = index, column = 3)
    unitCost.append(cell_obj.value)  

for index in range(4, row + 1):
    cell_obj = sheet_obj.cell(row = index, column = 6)
    sellingPrice.append(cell_obj.value)  

for index in range(4, row + 1):
    cell_obj = sheet_obj.cell(row = index, column = 4)
    reOrderLevel.append(cell_obj.value) 


def addingItems():
    driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-masterfiles/ion-content/div[2]/ion-grid/ion-row/ion-col/ion-item[10]/div[1]/div/ion-label').click()
    time.sleep(1)
    itemCode = 0

    while itemCode <= 30:
        if itemCode == 2:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode+1)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[2]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 1

        elif itemCode == 7:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode+1)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[3]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[14]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[15]/ion-col[2]/ion-item/ion-checkbox/button').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[1]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[4]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 3

        elif itemCode == 10:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-1)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[14]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[15]/ion-col[2]/ion-item/ion-checkbox/button').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[1]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[4]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 3

        elif itemCode == 13:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-3)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[3]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[14]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[15]/ion-col[2]/ion-item/ion-checkbox/button').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[1]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[4]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[4]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 3

        elif itemCode == 16:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-5)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[2]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 1

        elif itemCode == 17:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-5)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[14]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[15]/ion-col[2]/ion-item/ion-checkbox/button').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[3]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[5]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[4]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 3    

        elif itemCode == 20:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-7)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[2]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 1

        elif itemCode == 21:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-7)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[14]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[15]/ion-col[2]/ion-item/ion-checkbox/button').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[9]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[10]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[3]/div/div/ion-row/ion-col[1]/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[5]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[4]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 4   

        elif itemCode >= 25:    
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode-10)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[3]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[2]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 1

        else:
            driver.find_element_by_xpath('/html/body/ion-app/ng-component/ion-split-pane/ion-nav/page-items/ion-content/div[1]/ion-fab/button/ion-icon').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[1]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(itemCode+1)
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[2]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[3]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[4]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(item[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[5]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[2]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[6]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[7]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[8]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[3]/div/button/span/div[2]').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-alert/div/div[4]/button[2]/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[10]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(unitCost[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[11]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(sellingPrice[itemCode])
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[12]/ion-col/ion-item/div[1]/div/ion-input/input').send_keys(reOrderLevel[itemCode])
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[1]/ion-grid/ion-row[13]/ion-col/ion-item/div[1]/div/ion-select/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-popover/div/div[2]/div/ng-component/ion-list/ion-item[3]/div[1]/ion-radio/button/span').click()
            time.sleep(1)
            driver.find_element_by_xpath('/html/body/ion-app/ion-modal/div/page-items-crud/ion-content/div[2]/form/ion-card[2]/ion-row/ion-col/button[2]/span').click()
            time.sleep(1)
            itemCode += 1

addingItems()